name: "Bump Version"
description: "GitHub Action for Bumping Versions"
inputs:
  action:
    description: The release action ('prerelease' or 'postrelease')
    requred: true
  version-file:
    description: "The file that maintains the version (e.g. package.json, sly.json)"
    required: true
  repo-token:
    description: "The GitHub token for this repo. (https://docs.github.com/en/actions/reference/authentication-in-a-workflow#example-passing-github_token-as-an-input)"
runs:
  using: "node12"
  main: "dist/index.js"
